name: Simple Promotion

permissions:
  contents: write

on:
  push:
    branches:
      - DEV_BRANCH
      - QA_BRANCH

jobs:
  qa:
    if: github.ref == 'refs/heads/DEV_BRANCH'
    runs-on: ubuntu-latest
    environment: qa   # 🔐 approval

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          git config user.name "RonakSurana-2001"
          git config user.email "ronaksurana2017@github.com"
          git fetch origin
          git checkout QA_BRANCH
          git merge origin/DEV_BRANCH
          git push origin QA_BRANCH

  prod:
    needs: qa   
    if: needs.qa.result == 'success'
    runs-on: ubuntu-latest
    environment: prod   # 🔐 approval

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          git config user.name "RonakSurana-2001"
          git config user.email "ronaksurana2017@github.com"
          git fetch origin
          git checkout PROD_BRANCH
          git merge origin/QA_BRANCH
          git push origin PROD_BRANCH